/** Channel names shared by main and preload so a typo fails the build, not the app. */
export const IPC = {
  stateGet: 'state:get',
  stateChanged: 'state:changed',
  configGet: 'config:get',
  configSet: 'config:set',
  configChanged: 'config:changed',
  displaysList: 'displays:list',
  panelSetDisplay: 'panel:set-display',
  feedsStatus: 'feeds:status',
  feedsStatusChanged: 'feeds:status-changed',
  feedsRefresh: 'feeds:refresh',
  calendarAdd: 'feeds:calendar-add',
  calendarSetUrl: 'feeds:calendar-set-url',
  calendarRemove: 'feeds:calendar-remove',
  mailSetPassword: 'feeds:mail-set-password',
  blueskySetPassword: 'feeds:bluesky-set-password',
  microsoftStatus: 'microsoft:status',
  microsoftStatusChanged: 'microsoft:status-changed',
  microsoftConnect: 'microsoft:connect',
  microsoftDisconnect: 'microsoft:disconnect',
  microsoftLists: 'microsoft:lists',
  panelFocus: 'panel:focus',
  sourceLaunch: 'source:launch',
  pictureChoose: 'picture:choose',
  pictureList: 'picture:list',
  settingsOpen: 'settings:open',
  settingsClose: 'settings:close',
  taskAdd: 'task:add',
  taskToggle: 'task:toggle',
  taskRemove: 'task:remove',
  appQuit: 'app:quit'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
